Please Review My Mobile Portfolio Skeleton Version
efoosag/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2022-02-15 21:38 UTC by efoosag

This is the first request for this project. thank you for the review

2022-02-15 22:03 UTC, Lordkaito requested changes
Hi @efoosag, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [x] [OPTIONAL] This is not one mandatory requirement for you to pass this milestone, but it would be great if you can fix the horizontal scroll on your app. Right now, it does not really matter how big or small your screen is that you are going to have some horizontal scrolling. This may be caused by too big sizes used during your styling or because there's too much content inside any container. I would really recommend you to take a look and fix this issue.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 22:03 UTC, Lordkaito commented on index.html
> +          <h2>
- [ ] Please change this `h2` tag into an `h1` tag, as this is the main title of your page, you should be as semantic as possible.

2022-02-16 06:41 UTC, efoosag commented on index.html
> +      <section class="header">
I have effected the Changes

2022-02-16 06:42 UTC, efoosag commented on index.html
> +          <h2>
Resolved

2022-02-16 10:06 UTC, Whoistolu commented on index.html
> +      <section class="header">
👍🏽 All good now.

2022-02-16 10:06 UTC, Whoistolu commented on index.html
> +      <section>
👍🏽 All good now.

2022-02-16 10:06 UTC, Whoistolu commented on index.html
> +          <h2>
👍🏽 All good now.

2022-02-16 10:08 UTC, Whoistolu approved these changes
### Hi @efoosag,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 10:19 UTC, merged