Please My Mobile Portfolio Middle Section
efoosag/Portfolio-setup-and-mobile-version-skeleton pull request #2
Opened 2022-02-17 14:18 UTC by efoosag

Thank you for you review.

2022-02-17 15:00 UTC, AnselemOdims requested changes
### Hi @efoosag , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly make your PR title and summary more descriptive about the recent changes you made.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. Kindly tag me using @AnselemOdims for a quicker response.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-17 15:00 UTC, AnselemOdims commented on index.html
> +              <li><a href="#">javascript</a></li>
- [ ] The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are not links, so please remove the anchor `a` tag.

2022-02-17 15:00 UTC, AnselemOdims commented on index.html
> +          <div class="card1">
- [ ] Please make sure you your design sticks to the original [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) design guidelines(colors, fonts, margins, padding, width etc)
- [ ] Your button needs to match the original design. Please kindly adjust.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/154507495-a23e1218-2425-4c38-b662-c32f1a94e689.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/154507634-dc8ce6d0-c7e4-4e27-820d-bd716bc893ba.png)

2022-02-17 15:00 UTC, AnselemOdims commented on index.html
> +          <p>
- [ ] Please make sure you your design sticks to the original [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) design guidelines(colors, fonts, margins, padding, width etc)

### Your Design
![image](https://user-images.githubusercontent.com/43995830/154507882-a40331a9-95a1-4a4d-9e9e-26c8285747c7.png)

# Original Design
![image](https://user-images.githubusercontent.com/43995830/154508019-8a60969a-180d-45ed-a95f-6f71a1cafae4.png)

2022-02-18 08:37 UTC, efoosag commented on index.html
> +              <li><a href="#">javascript</a></li>
Done

2022-02-18 08:37 UTC, efoosag commented on index.html
> +        <div class="connect">LET’S CONNECT</div>
Done

2022-02-18 08:38 UTC, efoosag commented on index.html
> +          <div class="card1">
Done

2022-02-18 08:38 UTC, efoosag commented on index.html
> +          <p>
Done

2022-02-18 09:34 UTC, BenMukebo approved these changes
### *** Hi @efoosag, *** 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media3.giphy.com/media/xTQXENNW77nUsNVmV4/giphy.gif"/>
Cheers and Happy coding!👏👏👏

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 09:34 UTC, BenMukebo commented on index.html
> +        </div>
- [ Optional] Please implement  on the `get my resume and see project` button these actions as defined in this image  

<img width="487" alt="acti" src="https://user-images.githubusercontent.com/79058364/154655463-c9313c00-ae7c-44f2-8f05-bb95c4a51102.png">

2022-02-18 12:49 UTC, merged