New desktop portfolio branch
efoosag/Portfolio-setup-and-mobile-version-skeleton pull request #6
Opened 2022-02-25 13:47 UTC by efoosag

I could not understand why the desktop-portfolio-branch was not  working, so I created another one

2022-02-25 14:52 UTC, medaminedev66 requested changes
Hi @efoosag , :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- ✔️Your desktop version design is amazing and matches the Figma design
- ✔️Git/GitHub flow best practices have been followed

## Required Changes ♻️

- [x] Kindly try to solve the conflict before requesting another review to be able to merge your pull request when it's approved.
_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-25 14:52 UTC, medaminedev66 commented on styles.css
> +  }
- [ ] It would be better to add margins between elements to improve your UI design:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/77190203/155731768-718c9edc-482f-4355-a44d-ded9db4f0a95.png">

2022-02-25 14:52 UTC, medaminedev66 commented on index.html
>            <ul>
- Kindly add gaps between skills so your design matches the Figma design:
Your design:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/77190203/155732205-37371df6-181c-449b-ac38-85578a86bc86.png">

2022-02-25 14:52 UTC, medaminedev66 commented on styles.css
> +  }
- [ ] Following the project requirements, you should stick to the Figma design as much as you can. In the template that you have chosen the position of the image in the card is different in each card. which in your design is still at the same position in all your cards. See the comparison below 👇:
- Your design:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/77190203/155733507-d0e611af-ac56-4efd-b275-a2cfd4d80fab.png">


- Figma design:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/77190203/155733340-9e9cc1cb-dde6-4a93-b3d3-22aade64e21e.png">

2022-02-25 16:19 UTC, efoosag commented on styles.css
> +  }
done

2022-02-25 16:52 UTC, efoosag commented on index.html
>            <ul>
done

2022-02-25 16:52 UTC, efoosag commented on styles.css
> +  }
done

2022-02-25 18:13 UTC, efoosag commented
Changes Made.
I await your re-review.
Thank you for the review.

On Fri, Feb 25, 2022 at 3:52 PM Amine Smahi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @efoosag <https://github.com/efoosag> , 👋
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> To Highlight
>
>    - ✔️Your desktop version design is amazing and matches the Figma design
>    - ✔️Git/GitHub flow best practices have been followed
>
> Required Changes ♻️
>
>    - Kindly try to solve the conflict before requesting another review to
>    be able to merge your pull request when it's approved.
>    *See the inline comments below for more required changes*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In styles.css
> <https://github.com/efoosag/Portfolio-setup-and-mobile-version-skeleton/pull/6#discussion_r814810712>
> :
>
> > +  h2 {
>
> +    display: flex;
>
> +  }
>
> +
>
> +  .card {
>
> +    display: inline-block;
>
> +  }
>
> +
>
> +  .card-even img {
>
> +    float: right;
>
> +    width: 50%;
>
> +    margin-right: 12px;
>
> +    margin-bottom: 12px;
>
> +  }
>
> +
>
> +  .card-odd img {
>
> +    float: right;
>
> +    width: 50%;
>
> +    margin-right: 12px;
>
> +    margin-bottom: 12px;
>
> +  }
>
>
>
>    - It would be better to add margins between elements to improve your
>    UI design:
>
> [image: image]
> <https://user-images.githubusercontent.com/77190203/155731768-718c9edc-482f-4355-a44d-ded9db4f0a95.png>
> ------------------------------
>
> In index.html
> <https://github.com/efoosag/Portfolio-setup-and-mobile-version-skeleton/pull/6#discussion_r814812953>
> :
>
> > @@ -75,8 +78,8 @@ <h2>Tonic</h2>
>
>            </div>
>
>          </div>
>
>          <div class="card">
>
> -          <div class="card1">
>
> -            <img src="./images/Snapshoot-Portfolio1.svg" alt="Card 1" />
>
> +          <div class="card-even">
>
> +            <img src="./images/Snapshoot-Portfolio1.svg" alt="Card 2" />
>
>            </div>
>
>            <h2>Multi-Post Stories</h2>
>
>            <ul>
>
>
>
>    - Kindly add gaps between skills so your design matches the Figma
>    design:
>    Your design:
>
> [image: image]
> <https://user-images.githubusercontent.com/77190203/155732205-37371df6-181c-449b-ac38-85578a86bc86.png>
> ------------------------------
>
> In styles.css
> <https://github.com/efoosag/Portfolio-setup-and-mobile-version-skeleton/pull/6#discussion_r814822813>
> :
>
> > +  .card {
>
> +    display: inline-block;
>
> +  }
>
>
>
>    - Following the project requirements, you should stick to the Figma
>    design as much as you can. In the template that you have chosen the
>    position of the image in the card is different in each card. which in your
>    design is still at the same position in all your cards. See the comparison
>    below 👇:
>    - Your design:
>
> [image: image]
> <https://user-images.githubusercontent.com/77190203/155733507-d0e611af-ac56-4efd-b275-a2cfd4d80fab.png>
>
>    - Figma design:
>
> [image: image]
> <https://user-images.githubusercontent.com/77190203/155733340-9e9cc1cb-dde6-4a93-b3d3-22aade64e21e.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/efoosag/Portfolio-setup-and-mobile-version-skeleton/pull/6#pullrequestreview-893739616>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXBC6B73ADCJDIMI25TJYRTU46JULANCNFSM5PKKMCOA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> <efoosag/Portfolio-setup-and-mobile-version-skeleton/pull/6/review/893739616
> @github.com>
>

2022-02-25 20:41 UTC, MrBrN197 requested changes
Hi @efoosag  👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-25 20:41 UTC, MrBrN197 commented on index.html
> +          <ul>
- [ ] Hi, you've done well to fix all the other issues from the previous reviewer. Although I'm looking at your project and I don't think this particular issue mentioned by the reviewer was addressed. please fix this small issue and your project should be complete. 
- [ ] look at the little badges with the text "HTML", "CSS", "javascript". you can see that they are bundled together but the are supposed to have some space between them. 

Your Design | Reference Design
-|-
![image](https://user-images.githubusercontent.com/18730106/155799157-9bac7332-e2b6-4453-bab2-aff8d0737591.png)|![image](https://user-images.githubusercontent.com/18730106/155799589-af04dc92-0519-4490-b864-4e7eab8daaa4.png)

- [ ] notice that on the Figma there is space between the badges. maybe adding a `gap: ` property on the CSS should fix this

2022-02-26 00:05 UTC, nicupop729 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @efoosag, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 00:09 UTC, merged